### ISSUE TITLE
High Sierra feature – Caps Lock to switch languages

### ISSUE THREAD

**Issue by usr-sse2** [RehabMan/OS-X-Voodoo-PS2-Controller#142]
macOS High Sierra adds a new feature – switching keyboards with Caps Lock. (It's only for system-provided layouts, no Russian BG46).
![2017-12-22 17 41 07](https://user-images.githubusercontent.com/446776/34301836-520c06c2-e73f-11e7-8f32-1eab93537027.png)
But with VoodooPS2 it's very buggy – most times double-press switches language and single-press activates Caps Lock if no keys pressed within 1 second after, but it's not always so. It should be related to the Sierra Caps Lock workaround and maybe to kCapsLockDoesLock.

**Comment by RehabMan** [comment]
The bugs are caused by the capslock bug workaround.
As long as we need the workaround (hardcoded in VoodooPS2Keyboard), caps lock cannot be remapped.

**Comment by RehabMan** [comment]
Capslock can be remapped with ACPI.
Refer to example: SSDT-Swap-LeftControlCapsLock.dsl

**Comment by frol** [comment]
According to Karabiner EventViewer, pressing CapsLock produces events in a wrong order: key_up -> key_down instead of key_down -> key_up.

Does the remapping CapsLock <-> LeftControl intend to help with the issue and fix the CapsLock button or is it just breaking another button instead of CapsLock?

P.S. I also use CapsLock as a layout switcher and I would like to fix this...

UPD1: Removing [the workaround](https://github.com/acidanthera/VoodooPS2/blob/78f7704/VoodooPS2Keyboard/VoodooPS2Keyboard.cpp#L1747-L1767) resulted in that a single CapsLock press (down + up) produces only a single event `key_down` or `key_up` (it is toggling).

**Comment by frol** [comment]
FYI, I have patched the issue for myself: https://github.com/acidanthera/bugtracker/issues/435#issuecomment-529858985
