### ISSUE TITLE
x220 no edge scroll and middle scroll act like show desktop

### ISSUE THREAD

**Issue by Polishapple** [RehabMan/OS-X-Voodoo-PS2-Controller#72]
hi, latest version of voodoops2. Edge scroll (touchpad) isn't working, also middle scroll button act like show desktop button (works same as f11 shortcut)

**Comment by RehabMan** [comment]
Edge scrolling is disabled in the default Info.plist.  Feature is still there but requires a configuration override.  See VerticalScrollDivisor and HorizontalScrollDivisor and related code.  Current setting is by design.

No direct "middle scroll button" support as that is something specific to your hardware.  If you want something else to happen, you'll need to debug the protocol and implement the code.
