### ISSUE TITLE
Synaptics touchpad tracking issues (usr-sse2)

### ISSUE THREAD

**Issue by Petapton** [RehabMan/OS-X-Voodoo-PS2-Controller#96]
Hi, I'm using usr-sse2 version of the kext.
My trackpad is a Synaptics without separate buttons and while I'm dragging (using physical button) pointer goes down left, as trackpad tracks a finger in the bottom left corner. The only way to make it work is to press button with a nail, so trackpad registers click, but doesn't see the finger. Any help? Thanks

**Comment by usr-sse2** [comment]
I have such trackpad too, and such dragging never worked for me with RehabMan's version. Do I need to enable some option?

**Comment by RehabMan** [comment]
Dragging works fine here.  In 10.12, you enable it in SysPrefs->Accessibility.

**Comment by usr-sse2** [comment]
This discussion is not about dragging with one finger, which works, but about dragging with two fingers – one holding the button and another moving the cursor.


Strange – it sometimes works and sometimes doesn't, will check in the official 1.8.25 later. Also trying to click with physical buttons has always been very unreliable because while I click, the cursor moves.

**Comment by RehabMan** [comment]
It works just fine here.
